# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31d397becac3a4074b95a4ce5433dd44b3e02ebd23f09feccc249ba27609d6b2901256032ab2ad047a268db5f18177c1b6a7acebfe38981502022fb734485c77

test:
  secret_key_base: e7961685a61e47f909f904c0bd37479862d68c487d252058d66165848595210b356446f2aab2e280ccdfded9f3050ececb01960d5907acc02460d0b8125715e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
